---

- name: Check if config variable passed
  fail:
    msg: "firewall configuration has not been defined"
  when: firewall_config|default(False) == False

- name: Install iptables-persistant
  action: apt name=iptables-persistent state=present
  sudo: true

- name: Make sure iptables is started
  service: name=ufw state=started
  sudo: true

- name: Make sure iptables-persistent is started
  service: name=iptables-persistent state=started
  sudo: true

- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes
  sudo: true

  # Here we search port in a list, so every comment must have port name.
- name: Set input TCP rules
  command: /sbin/iptables -I INPUT 1 -p tcp -s {{ item.ip }} --dport {{ item.port }} -j ACCEPT -m comment --comment "{{ item.name }}"
  when: iptablesrules.stdout.find("http") == -1
  with_items: firewall
  sudo: true

- name: Allow all output (TODO)
  command: /sbin/iptables -I OUTPUT -d 0/0 -j ACCEPT
  sudo: true

- name: Save iptables
  shell: iptables-save > /etc/iptables/rules.v4
  sudo: true

- name: Restart iptables
  service:
    name: ufw
    state: restarted
  sudo: true


