---

- name: Check if config variable passed
  fail:
    msg: "firewall configuration has not been defined"
  when: firewall_config|default(False) == False

- name: Install iptables-persistant
  action: apt name=iptables-persistent state=present
  sudo: true

- name: Make sure iptables is started
  service: name=ufw state=started
  sudo: true

- name: Make sure iptables-persistent is started
  service: name=iptables-persistent state=started
  sudo: true

- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes
  sudo: true

- name: Flush rules
  shell: "{{ item }}"
  with_items:
      - /sbin/iptables -F OUTPUT
      - /sbin/iptables -F INPUT

- name: Set input TCP rules
  command: /sbin/iptables -A INPUT -p tcp -s {{ item.ip }} --dport {{ item.port }} -j ACCEPT -m state --state NEW,ESTABLISHED -m comment --comment "{{ item.name }}"
  #when: iptablesrules.stdout.find({{ item.name }}) == -1
  with_items: firewall
  sudo: true

- name: Allow only current connections
  shell: "{{ item }}"
  with_items:
    - /sbin/iptables -A OUTPUT -o lo -j ACCEPT
    #- /sbin/iptables -A OUTPUT -m state --state ESTABLISHED -j ACCEPT
    #- /sbin/iptables -A OUTPUT -j REJECT
    - /sbin/iptables -A INPUT -i lo -j ACCEPT
    #- /sbin/iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT
    - /sbin/iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    - /sbin/iptables -A INPUT -j REJECT
  sudo: true

#- name: Set unlimited traffic for loopback
#  shell: /sbin/iptables -A {{ item }} lo -j ACCEPT
#  with_items:
#      - "INPUT -i"
#      - "OUTPUT -o"
#  sudo: true

- name: Save iptables
  shell: iptables-save > /etc/iptables/rules.v4
  sudo: true

- name: Restart iptables
  service:
    name: ufw
    state: restarted
  sudo: true

